blank_issues_enabled: false
contact_links:
    - name: Contributing to Codewars API Wrapper
      url: https://github.com/YisusChrist/codewars-api-wrapper/blob/main/CONTRIBUTING.md
      about: Guidelines for how to report an issue.
    - name: Support
      url: https://github.com/YisusChrist/codewars-api-wrapper/discussions
      about: Ask the community for support
    - name: Documentation
      url: https://github.com/YisusChrist/codewars-api-wrapper/wiki
      about: Many questions might be already answered here.
